### PR TITLE
fix: skill creation and clone returns 'no skill repository found'

### LINKED ISSUE #234: Various operations result in a Git error "No skill repository found"
**Describe the bug**

The extension is unable to create new Alexa hosted python skills using Python runtimes.

**To Reproduce**

1. Navigate to Skills Management, select "Create a skill"
2. Give it a name, change the Hosting runtime to "Alexa-Hosted (Python)", select a local directory
3. Click Create
4. Toast error appears: "Skill creation failed. Reason: Failed to create a hosted skill. Reason: Git folder setup failed for <path>/<skillname> Reason: No skill repository found.

Alternative steps to reproduce the behavior:
1. Attempt to download and edit an existing skill

### PR DESCRIPTION
**Pull request by tydonelson**
Fixes #234 

## Description
The built-in vscode APIs for git management are failing to retrieve repositories in our environment, so for now we will fall back to executing git via the shell (some operations were already running through the shell). 

Adds a `getCurrentBranch` operation to the git terminal helper to facilitate the transition.

Also contains some ESLint corrections in the file `src/utils/cloneSkillHelper.ts`, mostly around usage before declaration.

## Testing
Manually tested, as well as added a unit tests around git helper functions:
image

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [X] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [X] I have read the **README** document
- [X] I have added tests to cover my changes
- [X] All new and existing tests passed
- [X] My commit message follows [Conventional Commit Guideline](https://conventionalcommits.org/)

## License

- [X] By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: src/askContainer/commands/cloneSkill/cloneHostedSkillManager.ts [hunk 1]
```diff
@@ -41,29 +40,15 @@ export class CloneHostedSkillManager extends AbstractCloneSkillManager {
         throw new AskError("Failed to retrieve hosted skill repo URL from the service.");
       }
       await this.downloadGitCredentialScript(this.fsPath, this.context);
+   
       gitHelper.init();
       gitHelper.configureCredentialHelper(repoUrl, this.profile, skillId);
       gitHelper.addOrigin(repoUrl);
+      gitHelper.fetchAll();
+      gitHelper.checkoutBranch("prod")
+      gitHelper.checkoutBranch("master");
```
Comment (doiron) [inline src/askContainer/commands/cloneSkill/cloneHostedSkillManager.ts:49]: huh?

**Review by doiron — APPROVED** [review]

File: src/askContainer/commands/cloneSkill/cloneHostedSkillManager.ts (hunk 1 above)
Comment (doiron) [reply src/askContainer/commands/cloneSkill/cloneHostedSkillManager.ts:49]: I see it was doing the same as well before.  I just don't understand why it's doing this branch change twice. some hack to pull both down locally I presume?

Comment (tydonelson) [reply src/askContainer/commands/cloneSkill/cloneHostedSkillManager.ts:49]: Right, I believe the purpose is to pull both down locally and have the upstream set
