### PR TITLE
fix: correct AbstractCommand for context menus

### LINKED ISSUE #227: Error while trying to register a device for skill testing in VS Code
I was setting up development and testing of Alexa Hosted skill in Visual Studio Code and was following this document - https://developer.amazon.com/de-DE/docs/alexa/ask-toolkit/vs-code-testing-simulator.html

When I tried to register a device for testing I got following error -

_Error running command askContainer.skillsConsole.deviceRegistry: Cannot read properties of undefined (reading 'CommandType'). This is likely caused by the extension that contributes askContainer.skillsConsole.deviceRegistry._

**To Reproduce**

1. Go to 'Skills Management'
2. Click on ellipsis (…) 
3. Click on 'Register Device'
5. Tried the same after closing and opening the Visual Code
6. Open `ASK Toolkit` Output window, and provide the logs - No logs printed
7. When tried other options under Skills Management like Profile Manager then a new error was shown -

_Error running command ask.init: Cannot read properties of undefined (reading 'CommandType'). This is likely caused by the extension that contributes ask.init._

**Context**
-   OS: Windows 10
-   Visual Studio Code Version: 1.74.0
-   Alexa Skill Toolkit Version:

**Additional context**

### PR DESCRIPTION
**Pull request by tonyhallett**
## Description
Context menu commands do not work.

## Motivation and Context
fixes #227 that has been bizarrely closed in favour of a workaround.

## Testing
https://github.com/tonyhallett/ask-toolkit-for-vscode/blob/fix-closed-issue-227/test/askContainer/commands/deviceRegistry.test.ts

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [x] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [x] I have read the **README** document
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed
- [x] My commit message follows [Conventional Commit Guideline](https://conventionalcommits.org/)

## License

- [x] By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: src/runtime/lib/API.ts [hunk 1]
```diff
@@ -76,7 +76,7 @@ export abstract class AbstractCommand<T> implements GenericCommand, Command {
   }
 
   private async _invoke(commandName: string, ...args: any[]): Promise<T> {
-    const typeArg = args.find((arg) => arg.CommandType);
+    const typeArg = args.find((arg) => arg && arg.CommandType);
```
Comment (tydonelson) [inline src/runtime/lib/API.ts:79]: We could probably condense `arg && arg.CommandType` to `arg?.CommandType`

Great fix :)

**Comment by tydonelson** [comment]
Thanks for much for the fix @tonyhallett ! Sorry for the confusion, we had closed the other issue in favor to indicate the the presence of the workaround to resolve the immediate issue and were tracking the underlying issue elsewhere, which wasn't readily apparent here. I just pulled down your change and verified it, looks great!

File: src/runtime/lib/API.ts (hunk 1 above)
Comment (tonyhallett) [reply src/runtime/lib/API.ts]: done

**Review by tydonelson — APPROVED** [review]
