### PR TITLE
fix: update webview forms to not redirect after submission. Fixes #123, #124

### LINKED ISSUE #123: Test Skill / Simulator goes blank
**Describe the bug**

When using the Skill Simulation window, after sending the first utterance to the skill, the window goes completely blank and cannot type a second one or view the JSON Input or Output other than the debug console.  

**To Reproduce**

1. Open Test Skill > Open Simulator
2. Enter an utterance and click Send 

**Extension Logs**

[debug - 2021-05-06 16:52:30.417Z] Calling method: askContainer.skillsConsole.simulateSkill 
[debug - 2021-05-06 16:52:30.418Z] Calling method: simulateSkill.getHtmlForView 
[debug - 2021-05-06 16:52:30.418Z] Calling method: simulateSkill.checkSimulatorMode 
[debug - 2021-05-06 16:52:30.418Z] Calling method: renderView, args:  [{"name":"simulateSkill","js":true,"args":{"simulateCss":{"$mid":1,"path":"/vscode-resource/file///Users/escarrg/.vscode/extensions/ask-toolkit.alexa-skills-kit-toolkit-2.5.0/media/simulate.css","scheme":"https","authority":"66ac76f8-ea4f-41de-bb8f-6de56a030f22.vscode-webview-test.com"},"aplRenderUtils":{"$mid":1,"path":"/vscode-resource/file///Users/escarrg/.vscode/extensions/ask-toolkit.alexa-skills-kit-toolkit-2.5.0/media/previewApl/aplRenderUtils.js","scheme":"https","authority":"66ac76f8-ea4f-41de-bb8f-6de56a030f22.vscode-webview-test.com"},"customJavascript":"https://66ac76f8-ea4f-41de-bb8f-6de56a030f22.vscode-webview-test.com/vscode-resource/file///Users/escarrg/.vscode/extensions/ask-toolkit.alexa-skills-kit-toolkit-2.5.0/node_modules/apl-viewhost-web/index.js","isAVSMode":false}}]
[debug - 2021-05-06 16:52:30.418Z] Calling method: interpolate, args:  [{"simulateCss":{"$mid":1,"path":"/vscode-resource/file///Users/escarrg/.vscode/extensions/ask-toolkit.alexa-skills-kit-toolkit-2.5.0/media/simulate.css","scheme":"https","authority":"66ac76f8-ea4f-41de-bb8f-6de56a030f22.vscode-webview-test.com"},"aplRenderUtils":{"$mid":1,"path":"/vscode-resource/file///Users/escarrg/.vscode/extensions/ask-toolkit.alexa-skills-kit-toolkit-2.5.0/media/previewApl/aplRenderUtils.js","scheme":"https","authority":"66ac76f8-ea4f-41de-bb8f-6de56a030f22.vscode-webview-test.com"},"customJavascript":"https://66ac76f8-ea4f-41de-bb8f-6de56a030f22.vscode-webview-test.com/vscode-resource/file///Users/escarrg/.vscode/extensions/ask-toolkit.alexa-skills-kit-toolkit-2.5.0/node_modules/apl-viewhost-web/index.js","isAVSMode":false}]
[debug - 2021-05-06 16:52:30.458Z] Calling method: renderView, args:  [{"name":"simulateSkill","js":true,"args":{"simulateCss":{"$mid":1,"external":"https://66ac76f8-ea4f-41de-bb8f-6de56a030f22.vscode-webview-test.com/vscode-resource/file///Users/escarrg/.vscode/extensions/ask-toolkit.alexa-skills-kit-toolkit-2.5.0/media/simulate.css","path":"/vscode-resource/file///Users/escarrg/.vscode/extensions/ask-toolkit.alexa-skills-kit-toolkit-2.5.0/media/simulate.css","scheme":"https","authority":"66ac76f8-ea4f-41de-bb8f-6de56a030f22.vscode-webview-test.com"},"aplRenderUtils":{"$mid":1,"external":"https://66ac76f8-ea4f-41de-bb8f-6de56a030f22.vscode-webview-test.com/vscode-resource/file///Users/escarrg/.vscode/extensions/ask-toolkit.alexa-skills-kit-toolkit-2.5.0/media/previewApl/aplRenderUtils.js","path":"/vscode-resource/file///Users/escarrg/.vscode/extensions/ask-toolkit.alexa-skills-kit-toolkit-2.5.0/media/previewApl/aplRenderUtils.js","scheme":"https","authority":"66ac76f8-ea4f-41de-bb8f-6de56a030f22.vscode-webview-test.com"},"customJavascript":"https://66ac76f8-ea4f-41de-bb8f-6de56a030f22.vscode-webview-test.com/vscode-resource/file///Users/escarrg/.vscode/extensions/ask-toolkit.alexa-skills-kit-toolkit-2.5.0/node_modules/apl-viewhost-web/index.js","isAVSMode":false}}]
[debug - 2021-05-06 16:52:30.459Z] Calling method: interpolate, args:  [{"simulateCss":{"$mid":1,"external":"https://66ac76f8-ea4f-41de-bb8f-6de56a030f22.vscode-webview-test.com/vscode-resource/file///Users/escarrg/.vscode/extensions/ask-toolkit.alexa-skills-kit-toolkit-2.5.0/media/simulate.css","path":"/vscode-resource/file///Users/escarrg/.vscode/extensions/ask-toolkit.alexa-skills-kit-toolkit-2.5.0/media/simulate.css","scheme":"https","authority":"66ac76f8-ea4f-41de-bb8f-6de56a030f22.vscode-webview-test.com"},"aplRenderUtils":{"$mid":1,"external":"https://66ac76f8-ea4f-41de-bb8f-6de56a030f22.vscode-webview-test.com/vscode-resource/file///Users/escarrg/.vscode/extensions/ask-toolkit.alexa-skills-kit-toolkit-2.5.0/media/previewApl/aplRenderUtils.js","path":"/vscode-resource/file///Users/escarrg/.vscode/extensions/ask-toolkit.alexa-skills-kit-toolkit-2.5.0/media/previewApl/aplRenderUtils.js","scheme":"https","authority":"66ac76f8-ea4f-41de-bb8f-6de56a030f22.vscode-webview-test.com"},"customJavascript":"https://66ac76f8-ea4f-41de-bb8f-6de56a030f22.vscode-webview-test.com/vscode-resource/file///Users/escarrg/.vscode/extensions/ask-toolkit.alexa-skills-kit-toolkit-2.5.0/node_modules/apl-viewhost-web/index.js","isAVSMode":false}]
[debug - 2021-05-06 16:52:30.839Z] Calling method: simulateSkill.onReceiveMessageListener 
[verbose - 2021-05-06 16:52:30.839Z] Calling method: getSkillDetailsFromWorkspace 
[verbose - 2021-05-06 16:52:30.839Z] Calling method: getSkillFolderInWs 
[verbose - 2021-05-06 16:52:30.839Z] Calling method: doesWorkSpaceExist 
[verbose - 2021-05-06 16:52:30.839Z] Calling method: getAskResourceConfig 
[verbose - 2021-05-06 16:52:30.839Z] Calling method: getAskState 
[verbose - 2021-05-06 16:52:30.840Z] Calling method: getSkillManifestFromWorkspace 
[verbose - 2021-05-06 16:52:30.840Z] Calling method: getSkillMetadataSrc 
[verbose - 2021-05-06 16:52:30.840Z] Calling method: getAskResourceConfig 
[verbose - 2021-05-06 16:52:30.840Z] Calling method: getSkillNameFromLocales, args: [{"en-US":{"description":"Sample Full Description","examplePhrases":["Alexa open hello world","hello","help"],"keywords":[],"name":"MyInsuranceCompany","summary":"Sample Short Description"}},null]
[verbose - 2021-05-06 16:52:30.840Z] Calling method: simulateMessageHelper.handleSkillStatusMessageFromWebview 
[verbose - 2021-05-06 16:52:30.840Z] Calling method: simulateSkillHelper.checkSkillStatus 
[debug - 2021-05-06 16:52:30.840Z] Calling method: simulateSkill.onReceiveMessageListener 
[verbose - 2021-05-06 16:52:30.840Z] Calling method: getSkillDetailsFromWorkspace 
[verbose - 2021-05-06 16:52:30.840Z] Calling method: getSkillFolderInWs 
[verbose - 2021-05-06 16:52:30.840Z] Calling method: doesWorkSpaceExist 
[verbose - 2021-05-06 16:52:30.840Z] Calling method: getAskResourceConfig 
[verbose - 2021-05-06 16:52:30.840Z] Calling method: getAskState 
[verbose - 2021-05-06 16:52:30.840Z] Calling method: getSkillManifestFromWorkspace 
[verbose - 2021-05-06 16:52:30.840Z] Calling method: getSkillMetadataSrc 
[verbose - 2021-05-06 16:52:30.840Z] Calling method: getAskResourceConfig 
[verbose - 2021-05-06 16:52:30.840Z] Calling method: getSkillNameFromLocales, args: [{"en-US":{"description":"Sample Full Description","examplePhrases":["Alexa open hello world","hello","help"],"keywords":[],"name":"MyInsuranceCompany","summary":"Sample Short Description"}},null]
[verbose - 2021-05-06 16:52:30.840Z] Calling method: simulateMessageHelper.handleLocaleMessageFromWebview 
[verbose - 2021-05-06 16:52:31.172Z] Calling method: simulateMessageHelper.getInvocationName 
[debug - 2021-05-06 16:52:34.890Z] Calling method: simulateSkill.onReceiveMessageListener 
[verbose - 2021-05-06 16:52:34.890Z] Calling method: getSkillDetailsFromWorkspace 
[verbose - 2021-05-06 16:52:34.890Z] Calling method: getSkillFolderInWs 
[verbose - 2021-05-06 16:52:34.890Z] Calling method: doesWorkSpaceExist 
[verbose - 2021-05-06 16:52:34.890Z] Calling method: getAskResourceConfig 
[verbose - 2021-05-06 16:52:34.891Z] Calling method: getAskState 
[verbose - 2021-05-06 16:52:34.891Z] Calling method: getSkillManifestFromWorkspace 
[verbose - 2021-05-06 16:52:34.891Z] Calling method: getSkillMetadataSrc 
[verbose - 2021-05-06 16:52:34.891Z] Calling method: getAskResourceConfig 
[verbose - 2021-05-06 16:52:34.891Z] Calling method: getSkillNameFromLocales, args: [{"en-US":{"description":"Sample Full Description","examplePhrases":["Alexa open hello world","hello","help"],"keywords":[],"name":"MyInsuranceCompany","summary":"Sample Short Description"}},null]
[verbose - 2021-05-06 16:52:34.891Z] Calling method: simulateMessageHelper.handleUtteranceMessageFromWebview 
[verbose - 2021-05-06 16:52:34.891Z] Calling method: simulateSkillHelper.getSimulationResponse, args:  ["open octank insurance"]
[verbose - 2021-05-06 16:52:35.146Z] Retrying simulation request, attempt: 1 
[error - 2021-05-06 16:52:35.337Z] Simulation in progress. 

[verbose - 2021-05-06 16:52:35.838Z] Retrying simulation request, attempt: 2 
[error - 2021-05-06 16:52:36.044Z] Simulation in progress. 

[verbose - 2021-05-06 16:52:37.045Z] Retrying simulation request, attempt: 3 
[error - 2021-05-06 16:52:37.230Z] Simulation in progress. 

[verbose - 2021-05-06 16:52:39.234Z] Retrying simulation request, attempt: 4 
[verbose - 2021-05-06 16:52:39.431Z] Calling method: simulateSkillHelper.formatAlexaResponse 

**Expected behavior**

Skill simulation window should not blank out.

**Screenshots**

**Desktop (please complete the following information):**

OS: Darwin x64 20.4.0 (Big Sur 11.3)
Visual Studio Code Version:  1.56.0
Alexa Skills Toolkit Version: 2.5.0
Git Version: git version 2.31.1

**Additional context**

Tried downgrading to ASK 2.4 but the issue is the same. This used to work about a month ago. May have to do with the VS Code version.

### PR DESCRIPTION
**Pull request by nikhilym**
## Description
Traditionally, vscode webviews used electron's `webview` tag for rendering webviews. As of `vscode v1.56.x`, this has been changed to use `iframe` ([ref](https://code.visualstudio.com/updates/v1_56#_iframes-now-used-for-most-webviews)). This is causing our current webviews containing forms and submit buttons to break, since the button click is leading to automatic page refresh, which our current webviews are not capable of handling.

## Motivation and Context

- #124 , #123 . Both these issues are logged on vscode 1.56.0, and multiple devs have mentioned that these are working as expected in the previous versions. 
- Debugged through toggling the developer tools, putting breakpoints across webviews and js, to check where the flow is breaking to show an empty page.
- Incorporated #126 in this PR as well, so that all webview specific changes for v1.56.0 are tracked at one place.
- There are nit linter changes that came in due to eslint running on compatible file saves. Left it as is since they are as per the lint configuration.

## Testing

- Tested all the touched webviews to be working as expected in previous versions.
- Made sure that the fixes do not break the experience in older vscode versions.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [x] I have read the **README** document
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed
- [x] My commit message follows [Conventional Commit Guideline](https://conventionalcommits.org/)

## License

- [x] By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: media/aplResourceSync/aplResourceSync.js [hunk 1]
```diff
@@ -7,33 +7,34 @@
...
     });
 
-    document.getElementById("downloadApl").onsubmit = function downloadApl() { 
+    document.getElementById('downloadApl').onsubmit = function downloadApl() {
         const name = document.getElementById('name').value;
         vscode.postMessage({
             action: 'sync',
             name: name,
         });
+        return false;
```
Comment (ShenChen-Amazon) [inline media/aplResourceSync/aplResourceSync.js:32]: why return false ? this function should return void ? Is this a new requirement also ?

File: media/initialLogin/initialLogin.js [hunk 2]
```diff
@@ -1,13 +0,0 @@
-/*---------------------------------------------------------------------------------------------
```
Comment (ShenChen-Amazon) [inline media/initialLogin/initialLogin.js:1]: why this one deleted ? no longer used ?

**Review by ShenChen-Amazon — COMMENTED** [review]
where is the iframe change LOL ? I search this keyword on the code change but found nothing. Did i miss something ?

**Comment by ShenChen-Amazon** [comment]
One question, if we switch to use `iframe`, will people who use old verison of vscode get affected ?

File: media/aplResourceSync/aplResourceSync.js (hunk 1 above)
Comment (nikhilym) [reply media/aplResourceSync/aplResourceSync.js:32]: No. Here, we are listening to the `submit` event and triggering an action. If we return void, it means the submission checks are fine and the form should be submitted to the next navigation step. However, that is not the case in these webviews since we perform navigation through backend.

This is not a new requirement from vscode, but instead seems to be related to the vscode behavior change when changed from the `webview` tag to `iframe` tag

File: media/initialLogin/initialLogin.js (hunk 2 above)
Comment (nikhilym) [reply media/initialLogin/initialLogin.js:1]: Not used in the flow

**Comment by nikhilym** [comment]
> One question, if we switch to use `iframe`, will people who use old verison of vscode get affected ?

I tested this specifically in the older versions, and there seems to be no effect/ noticeable change.

**Comment by nikhilym** [comment]
> where is the iframe change LOL ? I search this keyword on the code change but found nothing. Did i miss something ?

@ShenChen-Amazon , check this in the latest vscode changelog : https://code.visualstudio.com/updates/v1_56#_iframes-now-used-for-most-webviews

**Review by rimolive — APPROVED** [review]

**Comment by nikhilym** [comment]
Thanks for the review @rimolive

**Comment by rimolive** [comment]
I ran the code for this PR in a sandbox environment and the issue is fixed. Any chance for someone else to approve the PR?

**Review by sattpat — APPROVED** [review]
:shipit:

**Review by ShenChen-Amazon — APPROVED** [review]
